id: I7F6A552E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T00:19:09+00:00'
last_modified: '2022-06-09T06:43:56.657790+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3167
  title: དབུ་མ་རྩ་བ་ཤེས་རབ་ཀྱི་མཆན་འགྲེལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6AA7:
      image_group_id: I1KG3199
      title: Volume 1 of dbu ma rtsa ba shes rab kyi mchan 'grel
      total_pages: 408
      order: 1
      base_file: 6AA7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
