id: P007862
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3167
  title: དབུ་མ་རྩ་བ་ཤེས་རབ་ཀྱི་མཆན་འགྲེལ
  author: ''
  volumes:
    4f3741315473409cb6a66f1ffc0ecad5:
      image_group_id: I1KG3199
      title: ''
      volume_number: 1
      total_pages: 408
ebook_metadata:
  title: དབུ་མ་རྩ་བ་ཤེས་རབ་ཀྱི་མཆན་འགྲེལ
  author: ''
  sku: P007862
  cover: cover.jpg
  layers:
  - pagination
